mkdir -p samples
folder=data/source_pdfs
for i in {1..10}
do
  echo '\documentclass{article}     \begin{document}{\Large This is a sample PDF file number '"$i"'} \newline Numen: '"$i$i G 99 87654 XYZ"'\newpage \Large page 2\end{document}' > $folder/sample_$i.tex
  pdflatex -output-directory=$folder $folder/sample_$i.tex
  sleep 1
  # remove auxiliary files generated by latex
  rm $folder/sample_$i.aux $folder/sample_$i.log $folder/sample_$i.fdb_latexmk $folder/sample_$i.fls $folder/sample_$i.synctex.gz
done